# Generated by Django 5.1 on 2024-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_oreder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shopapp.product'),
        ),
    ]
