# Generated by Django 5.1 on 2024-10-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_oreder_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
        migrations.RenameField(
            model_name='oreder',
            old_name='promovode',
            new_name='promocode',
        ),
    ]
