# Generated by Django 5.1.3 on 2025-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder',
            name='receipt',
            field=models.FileField(null=True, upload_to='orders/receipts'),
        ),
    ]
